#ifndef _MODFLEX_HARDWARE_H_
#define _MODFLEX_HARDWARE_H_

#include "../siflex02/hardware.h"

#undef TOSH_SET_PIN_DIRECTIONS
#undef TOSH_CLR_GREEN_LED_PIN
#undef TOSH_SET_GREEN_LED_PIN
#undef TOSH_CLR_YELLOW_LED_PIN
#undef TOSH_SET_YELLOW_LED_PIN
#undef TOSH_CLR_RED_LED_PIN
#undef TOSH_SET_RED_LED_PIN

#define TOSH_SET_PIN_DIRECTIONS() PORTF.DIRSET = 0x0e; PORTF.OUTSET = 0x0e
#define TOSH_CLR_GREEN_LED_PIN()  PORTF.OUTCLR = 0x08
#define TOSH_SET_GREEN_LED_PIN()  PORTF.OUTSET = 0x08
#define TOSH_CLR_YELLOW_LED_PIN() PORTF.OUTCLR = 0x04
#define TOSH_SET_YELLOW_LED_PIN() PORTF.OUTSET = 0x04
#define TOSH_CLR_RED_LED_PIN()    PORTF.OUTCLR = 0x02
#define TOSH_SET_RED_LED_PIN()    PORTF.OUTSET = 0x02

#endif
